#ifndef QQUEUEUTILITY_GLOBAL_H
#define QQUEUEUTILITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QQUEUEUTILITY_LIBRARY)
#  define QQUEUEUTILITY_EXPORT Q_DECL_EXPORT
#else
#  define QQUEUEUTILITY_EXPORT Q_DECL_IMPORT
#endif

#endif // QQUEUEUTILITY_GLOBAL_H
